// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/

//@version=4
//42quants.com
//@42piratas

strategy("Grid Bots Screening", overlay=false)

// INPUTS

res = input(type=input.resolution, defval="240", title="Resolution")
lookBack = input(title="Lookback", type=input.integer, defval=30, minval=2)
range = input(title="Upper & Lower Range %", type=input.integer, defval=25, minval=10)

screenList  = input(false, "═════════ Screening ════════")
s01 = input('BINANCE:REPUSDT', type=input.symbol)
s02 = input('BINANCE:ZRXUSDT', type=input.symbol)
s03 = input('BINANCE:MKRUSDT', type=input.symbol)
s04 = input('BINANCE:ONEUSDT', type=input.symbol)
s05 = input('BINANCE:DOGEUSDT', type=input.symbol)

s06 = input('BINANCE:BNBUSDT', type=input.symbol)
s07 = input('BINANCE:ATOMUSDT', type=input.symbol)
s08 = input('BINANCE:BTCUSDT', type=input.symbol)
s09 = input('BINANCE:XRPUSDT', type=input.symbol)
s10 = input('BINANCE:ETHUSDT', type=input.symbol)

s11 = input('BINANCE:GRTUSDT', type=input.symbol)
s12 = input('BINANCE:SNXUSDT', type=input.symbol)
s13 = input('BINANCE:THETAUSDT', type=input.symbol)
s14 = input('BINANCE:DOTUSDT', type=input.symbol)
s15 = input('BINANCE:LINKUSDT', type=input.symbol)

s16 = input('BINANCE:UNIUSDT', type=input.symbol)

// INDICATORS & VARIABLES

var upperLimitLine = line.new(na, na, na, na, color=color.red,  width= 3, extend=extend.none)
var lowerLimitLine = line.new(na, na, na, na, color=color.black,  width= 3, extend=extend.none)
var upperRangeLine = line.new(na, na, na, na, color=color.blue, width= 2, extend=extend.none)
var lowerRangeLine = line.new(na, na, na, na, color=color.green, width= 2, extend=extend.none)

var range_corr = 100/range

screenerFunc() =>

	highestHigh = highest(high, lookBack)
	lowestLow = lowest(low, lookBack)

	xAxisStartsAt = bar_index[lookBack]
	xAxisFinishesAt = bar_index

	upperLimit = highestHigh
	lowerLimit = lowestLow

	upperRange = highestHigh - ((highestHigh - lowestLow)/range_corr) 
	lowerRange = ((highestHigh - lowestLow)/range_corr) + lowestLow

	HighAboveUpperRange = high > upperRange
	LowBelowLowerRange = low < lowerRange

	occurrencesAboveTotal   = sum(HighAboveUpperRange ? 1 : 0, lookBack)
	occurrencesAboveSecondHalf = sum(HighAboveUpperRange ? 1 : 0, lookBack/2)
	occurrencesAboveFirstHalf  = occurrencesAboveTotal - occurrencesAboveSecondHalf

	occurrencesBelowTotal   = sum(LowBelowLowerRange ? 1 : 0, lookBack)
	occurrencesBelowSecondHalf = sum(LowBelowLowerRange ? 1 : 0, lookBack/2)
	occurrencesBelowFirstHalf  = occurrencesBelowTotal - occurrencesBelowSecondHalf

	// SCREENING

	triggerA = occurrencesAboveFirstHalf >= 1 ? true : false
	triggerB = occurrencesAboveSecondHalf >= 1 ? true : false
	triggerC = occurrencesBelowFirstHalf >= 1 ? true : false
	triggerD = crossunder(low, lowerRange)

	triggerA and triggerB and triggerC and triggerD

c01 = security(s01, res, screenerFunc())
c02 = security(s02, res, screenerFunc())
c03 = security(s03, res, screenerFunc())
c04 = security(s04, res, screenerFunc())
c05 = security(s05, res, screenerFunc())

c06 = security(s06, res, screenerFunc())
c07 = security(s07, res, screenerFunc())
c08 = security(s08, res, screenerFunc())
c09 = security(s09, res, screenerFunc())
c10 = security(s10, res, screenerFunc())

c11 = security(s11, res, screenerFunc())
c12 = security(s12, res, screenerFunc())
c13 = security(s13, res, screenerFunc())
c14 = security(s14, res, screenerFunc())
c15 = security(s15, res, screenerFunc())

c16 = security(s16, res, screenerFunc())

// ALERTS
alertcondition(condition=c01, title="Alert", message="Grid Bot Alert!")
alertcondition(condition=c02, title="Alert", message="Grid Bot Alert!")
alertcondition(condition=c03, title="Alert", message="Grid Bot Alert!")
alertcondition(condition=c04, title="Alert", message="Grid Bot Alert!")
alertcondition(condition=c05, title="Alert", message="Grid Bot Alert!")

alertcondition(condition=c06, title="Alert", message="Grid Bot Alert!")
alertcondition(condition=c07, title="Alert", message="Grid Bot Alert!")
alertcondition(condition=c08, title="Alert", message="Grid Bot Alert!")
alertcondition(condition=c09, title="Alert", message="Grid Bot Alert!")
alertcondition(condition=c10, title="Alert", message="Grid Bot Alert!")

alertcondition(condition=c11, title="Alert", message="Grid Bot Alert!")
alertcondition(condition=c12, title="Alert", message="Grid Bot Alert!")
alertcondition(condition=c13, title="Alert", message="Grid Bot Alert!")
alertcondition(condition=c14, title="Alert", message="Grid Bot Alert!")
alertcondition(condition=c15, title="Alert", message="Grid Bot Alert!")

alertcondition(condition=c16, title="Alert", message="Grid Bot Alert!")

// PAINTBRUSH/LABEL

scr_label = 'Screener: \n##########\n'

scr_label := c01  ? scr_label + s01 + '\n' : scr_label
scr_label := c02  ? scr_label + s01 + '\n' : scr_label
scr_label := c03  ? scr_label + s01 + '\n' : scr_label
scr_label := c04  ? scr_label + s01 + '\n' : scr_label
scr_label := c05  ? scr_label + s01 + '\n' : scr_label

scr_label := c06  ? scr_label + s01 + '\n' : scr_label
scr_label := c07  ? scr_label + s01 + '\n' : scr_label
scr_label := c08  ? scr_label + s01 + '\n' : scr_label
scr_label := c09  ? scr_label + s01 + '\n' : scr_label
scr_label := c10  ? scr_label + s01 + '\n' : scr_label

scr_label := c11  ? scr_label + s01 + '\n' : scr_label
scr_label := c12  ? scr_label + s01 + '\n' : scr_label
scr_label := c13  ? scr_label + s01 + '\n' : scr_label
scr_label := c14  ? scr_label + s01 + '\n' : scr_label
scr_label := c15  ? scr_label + s01 + '\n' : scr_label

scr_label := c16  ? scr_label + s01 + '\n' : scr_label

lab_l = label.new(
	 bar_index, 0, scr_label,
	 color=color.gray,
	 textcolor=color.black,
	 style =  label.style_labeldown,
	 yloc = yloc.price)

label.delete(lab_l[1])

plot(0, transp = 100)

// ALERTS
if c01
    alert("GRID ALERT! " + s01, alert.freq_once_per_bar)
if c02
    alert("GRID ALERT! " + s02, alert.freq_once_per_bar)
if c03
    alert("GRID ALERT! " + s03, alert.freq_once_per_bar)
if c04
    alert("GRID ALERT! " + s04, alert.freq_once_per_bar)
if c05
    alert("GRID ALERT! " + s05, alert.freq_once_per_bar)

if c06
    alert("GRID ALERT! " + s06, alert.freq_once_per_bar)
if c07
    alert("GRID ALERT! " + s07, alert.freq_once_per_bar)
if c08
    alert("GRID ALERT! " + s08, alert.freq_once_per_bar)
if c09
    alert("GRID ALERT! " + s09, alert.freq_once_per_bar)
if c10
    alert("GRID ALERT! " + s10, alert.freq_once_per_bar)


if c11
    alert("GRID ALERT! " + s11, alert.freq_once_per_bar)
if c12
    alert("GRID ALERT! " + s12, alert.freq_once_per_bar)
if c13
    alert("GRID ALERT! " + s13, alert.freq_once_per_bar)
if c14
    alert("GRID ALERT! " + s14, alert.freq_once_per_bar)
if c15
    alert("GRID ALERT! " + s15, alert.freq_once_per_bar)

if c16
    alert("GRID ALERT! " + s16, alert.freq_once_per_bar)















